### ISSUE TITLE
start/stop script broken without daemon tools

### ISSUE THREAD

**Issue by nicky-johnstone** [qcode-software/naviserver#2]
bash function start-stop-daemon not defined

```
nick@debian:~$ /etc/init.d/naviserver start
[....] Starting naviserver daemon: default/etc/init.d/naviserver: 55: /etc/init.d/naviserver: start-stop-daemon: not found
```

Required in /etc/init.d/naviserver line 55

```
start_instance()
{
    CONF="/etc/naviserver/$INSTANCE.tcl"
    PIDFILE="/var/run/naviserver/$INSTANCE.pid"
    start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE --oknodo -- \
        -u $USER -g $GROUP -t $CONF >/dev/null 
}
```

**Comment by davidqc** [comment]
Thanks,
Is this on squeeze or wheezy?

**Comment by nicky-johnstone** [comment]
wheezy

**Comment by davidqc** [comment]
What's the output when you run "which start-stop-daemon"?

**Comment by nicky-johnstone** [comment]
No output from that command.

It looks like start-stop-daemon is located under /sbin/ though.

**Comment by davidqc** [comment]
Are you running the command from your user account?
What happens if you run "sudo which start-stop-daemon"

I think the init script was written with the assumption it'll always get
run by root (or via sudo to root). (which isn't necessarily a good assumption)

So `sudo /etc/init.d/naviserver start` should work for you.

PS. You might find the `stop` init command won't work either due to
a bug meaning the directory to store the pid isn't recreated properly.
A workaround is adding the following to `/etc/init.d/naviserver`:
At the top add

```
RUNDIR=/var/run/naviserver
```

Then change:

```
[ ! -d $RUNDIR ] && mkdir -p -m 755 $RUNDIR
```

to

```
[ ! -d $RUNDIR ] && mkdir -p -m 755 $RUNDIR && chown $USER:$GROUP $RUNDIR
```

**Comment by nicky-johnstone** [comment]
Ah, yes. It does indeed run with sudo.

```
nick@debian:~$ sudo /etc/init.d/naviserver start
[....] Starting naviserver daemon: default[19/Aug/2014:10:58:11][8486.7f9f26545700][-main-] Warning: config mimtypes: redefine predefined mime type for .adp value 'text/html' with different value: text/html; charset=iso-8859-1
[19/Aug/2014:10:58:11][8486.7f9f26545700][-main-] Notice: binder: started
. ok 
nick@debian:~$ [19/Aug/2014:10:58:11][8486.7f9f26545700][binder] Notice: binder: stopped
^C
```

Stop seems to be fine though:

```
nick@debian:~$ sudo /etc/init.d/naviserver stop
[ ok ] Stopping naviserver daemon: default.
```

Thanks for the assistance!

**Comment by davidqc** [comment]
No probs.
(The problem is the stop command lies and says it has stopped the daemon but it hasn't so running `ps aux | grep nsd` you may find the process still running!)

**Comment by nicky-johnstone** [comment]
Yeah, that was the case. The additions to `/etc/init.d/naviserver` have worked in making `stop` successful.
