### ISSUE TITLE
Build a package with debugging symbols 

### ISSUE THREAD

**Issue by bvw** [qcode-software/naviserver#4]
We need a way to track down why naviserver segfaults

**Comment by davidqc** [comment]
This is now available on debian.qcode.co.uk

```
$ apt-cache policy naviserver-dbg
naviserver-dbg:
  Installed: 4.99.7~20140909-1
  Candidate: 4.99.7~20140909-1
  Version table:
 *** 4.99.7~20140909-1 0
        500 http://debian.qcode.co.uk/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by bvw** [comment]
Can you please design a plan to deploy and test on LIVE so that we can identify what causes segfaults.

**Comment by davidqc** [comment]
Should we consider rolling out the official 4.99.7 first?
There are a lot of bugfixes in that release and I know Gustaf has been working hard on code quality. 
Could be that the problem is already fixed.
