### ISSUE TITLE
What is the difference between aol server and naviserver?

### ISSUE THREAD

**Issue by topstarnetwork** [qcode-software/naviserver#9]
What is the difference between aol server and naviserver?
Which one from both has more scability, features and functionalities, and why should I use one instead of the other one????

**Comment by davidqc** [comment]
Aolserver and Naviserver are very similar in their core functionality, but Naviserver is a fork of Aolserver and is being actively extended as technologies mature. (For instance the nsssl module has recently been updated to reflect current best practice in ssl configuration)

This repo is a Debian packaging repo and lags behind the main Naviserver release schedule. 

For your info the main Naviserver repo is here:
https://bitbucket.org/naviserver

And the mailing lists are here:
http://sourceforge.net/p/naviserver/mailman/
